export './colors.dart';
export './images.dart';
export './strings.dart';
export './styles.dart';
export 'package:velocity_x/velocity_x.dart';
export 'package:flutter/material.dart';
export 'package:get/get.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:image_picker/image_picker.dart';
